In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [2]:
vec = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
print((1/(1 + np.exp(-vec)))[-5:])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [3]:
x = np.array([3,1,4,2,6,1,4,8])
𝑦 = np.array([5,2,3,12,2,4,17,11])

# a) by using element-wise multiplication and np.sum,
print(np.sum(x * y))

# b) by using np.dot,
print(np.dot(x, y))

# c) by using np.matmul and transposition (x.T).
print(np.matmul(x.T, y))

225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [4]:
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2,1.0])
o = np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])

y = 1 / (1 + np.exp(np.sum(-(x * o))))
print(y)


0.2417699832615572


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [5]:
A = np.array([1, 2, 1, 3, 0, 1]).reshape(2, 3)
B = np.array([0.2, 0.3]).reshape(2, 1)

x = np.array([[1, 2, 3]]).T
y = np.matmul(A, x) + B
print(y)

[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [6]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [7]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [8]:
len(steam_df[steam_df['behavior-name'] == 'purchase']['user-id'].drop_duplicates())

12393

**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [9]:
len(
    steam_df[
        (steam_df['game-title'] == 'The Elder Scrolls V Skyrim') &
        (steam_df['behavior-name'] == 'purchase')
    ]
)

717

**Task 7.** How many purchases people made on average?

In [10]:
steam_df[steam_df['behavior-name'] == 'purchase'].groupby(['user-id']).sum()['value'].mean()

10.45033486645687

**Task 8.** Who bought the most games?

In [11]:
steam_df[
    steam_df['behavior-name'] == 'purchase'
].groupby(['user-id']).sum(['value']).idxmax()['value']

62990992

**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [12]:
steam_df[
    (steam_df['game-title'] == 'The Elder Scrolls V Skyrim') &
    (steam_df['behavior-name'] == 'play')
].groupby(['user-id']).sum(['value'])['value'].mean()

104.71093057607091

**Task 10.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [13]:
steam_df.loc[
    steam_df['behavior-name'] == 'play', ['game-title', 'value']
].groupby(['game-title']).sum().sort_values(by=['value'], ascending=False).reset_index().head(10)

game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7

**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [14]:
steam_df.loc[
    steam_df['behavior-name'] == 'play',
    ['game-title', 'user-id', 'value']
].groupby([
    'game-title', 'user-id'
]).sum().groupby([
    'game-title'
]).mean().sort_values(by='value', ascending=False).reset_index().head(10)

game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000

**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [15]:
steam_df_copy = steam_df.copy()
steam_df_copy['value'] = steam_df_copy['value'] - (steam_df_copy['behavior-name'] == 'purchase')
steam_df_copy = steam_df_copy.groupby([
    'game-title', 'user-id'
]).sum().groupby([
    'game-title'
]).mean().sort_values(by='value', ascending=False).reset_index().head(10)

print(steam_df_copy[['game-title', 'value']])

                    game-title        value
0      Eastside Hockey Manager  1295.000000
1              FIFA Manager 09   411.000000
2                    Perpetuum   400.975000
3        Football Manager 2012   385.572500
4        Football Manager 2014   382.185000
5        Football Manager 2010   345.439474
6        Football Manager 2011   333.435294
7  Out of the Park Baseball 16   330.400000
8        Football Manager 2013   310.659615
9        Football Manager 2015   307.381013


**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [16]:
c_steam_df = steam_df.copy()
c_steam_df.loc[c_steam_df['behavior-name'] == 'play', ['value']] = c_steam_df.loc[c_steam_df['behavior-name'] == 'play', ['value']].apply(lambda x: (1/(1 + np.exp(-(1/100)*x))))
print(c_steam_df.head(10))

     user-id                  game-title behavior-name     value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1  151603712  The Elder Scrolls V Skyrim          play  0.938774     0
2  151603712                   Fallout 4      purchase  1.000000     0
3  151603712                   Fallout 4          play  0.704746     0
4  151603712                       Spore      purchase  1.000000     0
5  151603712                       Spore          play  0.537181     0
6  151603712           Fallout New Vegas      purchase  1.000000     0
7  151603712           Fallout New Vegas          play  0.530213     0
8  151603712               Left 4 Dead 2      purchase  1.000000     0
9  151603712               Left 4 Dead 2          play  0.522235     0


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [70]:
genres = ml_df.set_index('movieId').genres.str.split('|', expand=True).stack().to_frame('genres').reset_index()
print(
  genres.groupby(['genres'])['movieId'].count().sort_values(ascending=False).reset_index().rename(columns={'movieId': 'n_users', 'genres': 'genre'})
)

                 genre  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47


**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [18]:
genres = ml_df.set_index(['movieId', 'rating']).genres.str.split('|', expand=True).stack().to_frame('genres').reset_index()
print(
  genres.groupby(['genres'])['rating'].mean().sort_values(ascending=False).reset_index().rename(columns={'genres': 'genre'})
)

                 genre    rating
0            Film-Noir  3.920115
1                  War  3.808294
2          Documentary  3.797785
3                Crime  3.658294
4                Drama  3.656184
5              Mystery  3.632460
6            Animation  3.629937
7                 IMAX  3.618335
8              Western  3.583938
9              Musical  3.563678
10           Adventure  3.508609
11             Romance  3.506511
12            Thriller  3.493706
13             Fantasy  3.491001
14  (no genres listed)  3.489362
15              Sci-Fi  3.455721
16              Action  3.447984
17            Children  3.412956
18              Comedy  3.384721
19              Horror  3.258195


**Task 17.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print first 10 in the form: title, average rating, bias.

In [19]:
movies_ratings = ml_df.groupby(['title'])['rating'].mean().reset_index()
averange_rating = ml_df['rating'].mean()
movies_ratings = movies_ratings.rename(columns={'rating': 'average_rating'})
movies_ratings['bias'] = movies_ratings['average_rating'] - averange_rating

print (movies_ratings.head(10))


# print(movies_ratings.sort_values(by=['bias'], ascending=False).head(10))

                                     title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843


**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print first 10 in the form: user_id, average rating, bias.

In [20]:
users_ratings = ml_df.groupby(['userId'])['rating'].mean().reset_index()
user_averange_rating = ml_df['rating'].mean()
users_ratings = users_ratings.rename(columns={'rating': 'average_rating'})
users_ratings['bias'] = users_ratings['average_rating'] - user_averange_rating

print(users_ratings.head(10))

   userId  average_rating      bias
0       1        4.366379  0.864822
1       2        3.948276  0.446719
2       3        2.435897 -1.065660
3       4        3.555556  0.053999
4       5        3.636364  0.134807
5       6        3.493631 -0.007926
6       7        3.230263 -0.271294
7       8        3.574468  0.072911
8       9        3.260870 -0.240687
9      10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task.

In [63]:
# Nie byłem w stanie wygenerować takich samych losowych wyników, jak w rozwiązaniu zadania. Każda metoda zwracała zupełnie inne wartości.
movies = [934, 2571, 3260, 5391, 6324, 6614, 7708, 89388, 104283, 164881]
users = [10, 276, 285, 356, 413, 427, 469, 486, 542, 543]

def func(x):
  return  float(x.values[0] > 0)

def cols(x):
  columns = []
  index = 0

  for column in x:
    if column[1] in movies:
      columns.append(index)
    
    index += 1

  return columns

table_df = ml_df[['userId', 'movieId', 'title', 'rating']].pivot_table(index='userId', columns=['movieId', 'title'], aggfunc=func, fill_value=0.0)
table_df.reset_index(inplace=True)
table_df = table_df.iloc[:, cols(table_df.columns)]
table_df.reset_index(drop=True, inplace=True)
table_df = table_df.iloc[users]
table_df.index += 1
table_df.columns = table_df.columns.map(lambda x: x[2])

for columnName in table_df.columns:
  table_df[columnName] = table_df[columnName].astype(float)

print(table_df)

     Father of the Bride (1950)  Matrix, The (1999)  Howards End (1992)  \
11                          0.0                 0.0                 0.0   
277                         0.0                 0.0                 0.0   
286                         0.0                 1.0                 0.0   
357                         0.0                 0.0                 0.0   
414                         0.0                 1.0                 0.0   
428                         0.0                 1.0                 0.0   
470                         0.0                 0.0                 0.0   
487                         0.0                 1.0                 0.0   
543                         0.0                 1.0                 0.0   
544                         0.0                 0.0                 0.0   

     Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)  \
11                                                 0.0                         
277           

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix for the MovieLens dataset. Print the submatrix of first 10 rows and 10 columns.

In [68]:
def func(x):
  return int(x.values[0] > 0)

table_df = ml_df.loc[ml_df['userId'] > 0, ['userId', 'movieId', 'title', 'rating']].pivot_table(index='userId', columns=['movieId', 'title'], aggfunc=func, fill_value=0).iloc[:9, :9]
table_df.columns = table_df.columns.map(lambda x: x[2])

result = np.zeros((10, 10))
result[1:10, 1:10] = table_df

print(result)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [36]:
def intersection(a, b):
  r = [value for value in a if value in b]
  return len(r)

user_movie_df = ml_df[['userId', 'movieId']].groupby(['userId'])['movieId'].apply(list).to_frame()[:9]

mat = np.zeros((10, 10))

for row in user_movie_df.itertuples():
  mat[row.Index, row.Index] = len(row.movieId)
  for comparing_row in user_movie_df[row.Index:].itertuples():
    mat[comparing_row.Index, row.Index] = intersection(row.movieId, comparing_row.movieId)
    mat[row.Index, comparing_row.Index] = intersection(row.movieId, comparing_row.movieId)

print(mat)




[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 232.   2.   7.  45.  13.  33.  26.  15.   5.]
 [  0.   2.  29.   0.   1.   1.   2.   3.   1.   0.]
 [  0.   7.   0.  39.   1.   1.   3.   0.   1.   0.]
 [  0.  45.   1.   1. 216.  12.  27.  22.   9.   1.]
 [  0.  13.   1.   1.  12.  44.  36.   9.  19.   0.]
 [  0.  33.   2.   3.  27.  36. 314.  14.  44.   2.]
 [  0.  26.   3.   0.  22.   9.  14. 152.   8.   6.]
 [  0.  15.   1.   1.   9.  19.  44.   8.  47.   0.]
 [  0.   5.   0.   0.   1.   0.   2.   6.   0.  46.]]


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. To prevent hanging your computer because of RAM shortage use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [38]:
def intersection(a, b):
  r = [value for value in a if value in b]
  return len(r)

user_movie_df = ml_df[['userId', 'movieId']].groupby(['movieId'])['userId'].apply(list).to_frame()[:9]

mat = np.zeros((10, 10))

for row in user_movie_df.itertuples():
  mat[row.Index, row.Index] = len(row.userId)
  for comparing_row in user_movie_df[row.Index:].itertuples():
    mat[comparing_row.Index, row.Index] = intersection(row.userId, comparing_row.userId)
    mat[row.Index, comparing_row.Index] = intersection(row.userId, comparing_row.userId)

print(mat)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 215.  68.  32.   2.  32.  58.  32.   5.  12.]
 [  0.  68. 110.  26.   3.  22.  36.  18.   6.   3.]
 [  0.  32.  26.  52.   1.  19.  25.  19.   4.   9.]
 [  0.   2.   3.   1.   7.   3.   2.   6.   1.   0.]
 [  0.  32.  22.  19.   3.  49.  24.  23.   4.   9.]
 [  0.  58.  36.  25.   2.  24. 102.  22.   5.   9.]
 [  0.  32.  18.  19.   6.  23.  22.  54.   4.   5.]
 [  0.   5.   6.   4.   1.   4.   5.   4.   8.   0.]
 [  0.  12.   3.   9.   0.   9.   9.   5.   0.  16.]]
